default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        types: [python]
        args:
          - "--line-length=120"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        types: [python]
        pass_filenames: false
        additional_dependencies:
          - types-protobuf
          - grpc-stubs
          - types-requests
          - opentelemetry-sdk>=1.21
          - opentelemetry-instrumentation>=0.40b0
        args: ["--config-file", "pyproject.toml", "."]
