# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from baserun.v1 import baserun_pb2 as v1_dot_baserun__pb2


class SpanSubmissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitSpan = channel.unary_unary(
            "/baserun.v1.SpanSubmissionService/SubmitSpan",
            request_serializer=v1_dot_baserun__pb2.SubmitSpanRequest.SerializeToString,
            response_deserializer=v1_dot_baserun__pb2.SubmitSpanResponse.FromString,
        )


class SpanSubmissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitSpan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SpanSubmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SubmitSpan": grpc.unary_unary_rpc_method_handler(
            servicer.SubmitSpan,
            request_deserializer=v1_dot_baserun__pb2.SubmitSpanRequest.FromString,
            response_serializer=v1_dot_baserun__pb2.SubmitSpanResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "baserun.v1.SpanSubmissionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SpanSubmissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitSpan(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/baserun.v1.SpanSubmissionService/SubmitSpan",
            v1_dot_baserun__pb2.SubmitSpanRequest.SerializeToString,
            v1_dot_baserun__pb2.SubmitSpanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
